hr:
  employee:
    smart:
      topLimit: 10.5
      middleLimit: 9
      lowerLimit: 8
      percentageForTop: 15
      percentageForMiddle: 14
      percentageForLower: 11
      percentageForRest: 8
      limits:
        1: 1
        2.5: 5
        11: 70
        4: 6
        10: 33
spring:
  profiles:
    active: smarta
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

